<?	
  //We don't want to laod all the scripts
  $this->layout()->setLayout('minimal');
?>
<div id='foafUrlContainer'>
                <?php if(property_exists($this,'publicUri') && $this->publicUri){
                                        echo("<div class='foafUrlTitle'>Your Public FOAF URI: </div><div class='foafUrl'>".$this->publicUri."</div>");

                } ?>

                <br/>

                <?php if(property_exists($this,'privateUri') && $this->privateUri){
                                echo("<div class='foafUrlTitle'>Your Private FOAF URI: </div><div class='foafUrl'>".$this->privateUri."</div>");

                } ?>

</div>
<div id="content">
	<div class="">
		<h3>
			Foaf Builder Advanced Writing Options
		</h3>

		<div id="garlik">
			<h2>Save</h2>
			<p>If you would like to save the private, public or both parts of your FOAF profile please select from the options below.

			<table cellspacing="10">
			<tr>
				<td>
					<form id="otherFormpublic" action="javascript:writePublic()">
						<input class="otherButton" type="submit" value="Public"/>
					</form>
				</td>
				<td>
					<form id="otherFormprivate" action="javascript:writePrivate()">
						<input class="otherButton" type="submit" value="Private"/>
					</form>
				</td>
				<td>
					<form id="otherFormpublicprivate" action="javascript:writePublicAndPrivate()">
						<input class="otherButton" type="submit" value="Both"/>
					</form>
				</td>
				<td id='saveInfo'>

        			</td>
				<td>
                			<img src='/images/ajax-loader.gif' id='ajaxLoader'/>
			        </td>

			</tr>
			</table>
		</div>
		

		<div id="download">
			<h2>Download files</h2>
			<p>If you would like to download either the private or public parts of your FOAF file please select one of the buttons below.</p>

			<table cellspacing="10">
			<tr>
				<td>
					<form action="javascript:write('public')">
						<input class="otherButton" type="submit" value="Public"/>
					</form>
				</td>
				<td>
					<form action="javascript:write('private')">
						<input class="otherButton" type="submit" value="Private"/>
					</form>
				</td>
			</tr>
			</table>
		</div>

	
		<div id="webdav">
			<h2>Write to WebDAV</h2>
			<p>If you would like to write to a WebDAV resource, please complete the forms below</p>
			<table cellspacing="10">
			<tr>
				<td>
					<form id="webdavFormpublic" action="javascript:writePublicWebDav()">
FOAF URI: <input type="text" name="uri" id="webdavpublicuri" maxlength="800" value="http://"/><br/>
Username: <input type="text" name="username" id="webdavpublicusername" maxlength="800" value=""/><br/>
Password:  <input type="password" name="password" id="webdavpublicpassword" maxlength="800" value=""/><br/><br/>
<input class="webdavpubButton" type="submit" value="Public"/>
					</form>
				</td>
				<td id='webdavpublicsaveInfo'>
        			</td>
			</tr>
			<tr>
				<td>
					<form id="webdavFormprivate" action="javascript:writePrivateWebDav()">
FOAF URI: <input type="text" name="uri" id="webdavprivateuri" maxlength="800" value="http://"/><br/>
Username: <input type="text" name="username" id="webdavprivateusername" maxlength="800" value=""/><br/>
Password: <input type="password" name="password" id="webdavprivatepassword" maxlength="800" value=""/><br/><br/>
<input class="webdavpriButton" type="submit" value="Private"/>
					</form>
				</td>
				<td id='webdavprivatesaveInfo'>
        			</td>
			</tr>
			</table>

		</div>

		<div id="oauth">
			<h2>Write to OAuth</h2>
			      <p>
				Coming soon...
			      </p>
		</div>


		<div id="builder">
			<h2>Back to the builder</h2>
			<table cellspacing="10">
			<tr>
				<td>
					<form id="builder" action="/builder">
						<input class="otherButton" type="submit" value="Builder"/>
					</form>
				</td>
			</tr>
			</table>

		</div>
  </div>
</div><!-- end content -->
<!-- footer -->
