<h3>Add FOAF File below:</h3>
<?
//TODO: need to generate forms for input elements to aid with eventual w3c compliance
?>
<p>Shove Your FOAF Document URI in here:</p>
<table cellspacing="10">
	<tr>
		<td>
			<form action = "javascript:loadFoaf(currentPage);">
				<input type = 'text' id= 'foafUri' name = 'foafUri'/>
				<input type = 'submit' value = 'Load'/>
			</form>
		</td>
		<td>
			<form action = "javascript:renderOther();">
				<input type = 'text' id= 'writeUri' name = 'writeUri'/>
				<input type = 'submit' value = "Write" />
			</form>
		</td>
		<td>
			<? //FIXME: sort this out so that it saves whichever page you're on ?>
			<form action = "javascript:saveFoaf();">
				<input type = 'submit' value = 'Save'/>
			</form>
		</td>
		<td>
			<form action = "javascript:clearFoaf();">
				<input type = 'submit' value = 'Clear'/>
			</form>
		</td>
	</tr>
</table>
<div id="leftCol">
<form action="javascript:alert('TODO: implement this Luke!');">
	<? //TODO: perhaps the load-the-basics name should be generated somehow ?>
		<div onclick="loadFoaf('load-the-basics');" class="editorElement">
			<div id="load-the-basics" class="editorTitle">
				<img alt="basics" class="editorElementIcon" src="/images/basics_icon.gif"/>
				<div class="editorTitleText">The basics <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Title <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Given Name <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleEven">
				Family Name <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Real Name <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleEven">
				Nickname <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Birthday <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Homepage <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-contact-details');" class="editorElement">
			<div id='load-contact-details' class="editorTitle">
				<img alt="contact" class="editorElementIcon" src="/images/contact_icon.gif"/>
				<div class="editorTitleText">Contact details <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Email <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Phones <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleEven">
				Addresses <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Online <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-pictures');" class="editorElement">
			<div id="load-pictures" class="editorTitle">
				<img alt="pictures" class="editorElementIcon" src="/images/pictures_icon.gif"/>
				<div class="editorTitleText">Pictures <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Main Image <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Others <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-locations');" class="editorElement">
			<div id="load-locations" class="editorTitle">
				<img alt="accounts" class="editorElementIcon" src="/images/accounts_icon.gif"/>
				<div class="editorTitleText">Locations <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Nearest Airport <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				I'm Based Near <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-accounts');" class="editorElement">
			<div id="load-accounts" class="editorTitle">
				<img alt="accounts" class="editorElementIcon" src="/images/accounts_icon.gif"/>
				<div class="editorTitleText">Accounts <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Identity <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Sharing <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleEven">
				Network <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-friends');" class="editorElement">
			<div id="load-friends" class="editorTitle">
				<img alt="friends" class="editorElementIcon" src="/images/friends_icon.gif"/>
				<div class="editorTitleText">Friends <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Work <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Personal <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-blogs');" class="editorElement">
			<div id="load-blogs" class="editorTitle">
				<img alt="blogs" class="editorElementIcon" src="/images/blogs_icon.gif"/>
				<div class="editorTitleText">Blogs <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Reader <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Writer <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-interests');" class="editorElement">
			<div id="load-interests" class="editorTitle">
				<img alt="interests" class="editorElementIcon" src="/images/interests_icon.gif"/>
				<div class="editorTitleText">Interests <div class='editorSubOptionsText'>private</div></div>
			</div>
			<div class="editorSubTitleEven">
				Professional <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
			<div class="editorSubTitleOdd">
				Personal <input type='checkbox' onclick="alert('TODO: These arent plumbed in yet and may end up being deleted.');" class='privateCheckbox' name="TODO" value="private">
			</div>
		</div>
		<div onclick="loadFoaf('load-other');" class="editorElement">
			<div id="load-other" class="editorTitle">
				<img alt="other" class="editorElementIcon" src="/images/other_icon.gif"/>
				<div class="editorTitleText">Other <div class='editorSubOptionsText'>private</div></div>
			</div>
		</div>
	</form>
</div><!-- end leftCol -->

<div class="rightCol" id="personal">


</div>
<!-- hidden div for autocomplete to work for airports. TODO: configure this in a more straightforward way -->
	<div id='airport_autocomplete'>
	<input type="text" value="Find an airport" onclick="if(this.value=='Find an airport'){this.value='';}" id="CityLocal" autocomplete="off" class="ac_input" style=""/>
</div>
	