<h3>Add FOAF File below:</h3>
<?
//TODO: move some of this data out of here
//TODO: decide whether to populate entirely in javsacript or not and tidy this up accordingly.
?>
<p>Shove Your URI in here:</p>
<form action = "javascript:loadFoaf();">
	<input type = 'text' id= 'foafUri' name = 'foafUri'/>
	<input type = 'submit' value = 'Load'/>
</form>
<form action = "javascript:saveFoaf();">
	<input type = 'submit' value = 'Save'/>
</form>
<form action = "javascript:clearFoaf();">
	<input type = 'submit' value = 'Clear'/>
</form>
<form action = "javascript:writeFoaf();">
	<input type = 'text' id= 'writeUri' name = 'writeUri'/>
	<input type = 'submit' value = "Write" />
</form>
<div id="personal">
	<div id="foafName_container">
		<p>
			<span>Name: </span>
			<input id='foafName_0' value='<? echo($this->name);?>'/> 
		</p>
	</div>
	<div id="foafNick_container">
		<p>
			<span>Nicknames: </span>
			<input id='foafNick_0' value='<? echo($this->nick);?>'>
		</p>
	</div>
	<div id="foafUsername_container">
		<p>
			<span>Usernames: </span>
			<input id='foafUsername_0' value='<? echo($this->username);?>'> 
		</p>
	</div>
	<div id="foafLocation_container">
		<p>
			<span>Location: </span>
			<input id='foafLocation_0' value='<? echo($this->location);?>'>
		</p>
	</div>
	<div id="foafBirthday_container">
		<p>
			<span>Birthday (foafBirthday): </span>
			<input id='foafBirthday_0' value='<? echo($this->birthday);?>'> 
		</p>
	</div>
	<div id="foafBirthday_container">
		<p>
			<span>Birthday (fromBio): MAKE NOT WRITEABLE?</span>
			<input id='bioBirthday_0' value='<? echo($this->birthday);?>'> 
		</p>
	</div>
	<div id="foafBirthday_container">
		<p>
			<span>Birthday, (foafDateOFBirth): </span>
			<input id='foafDateOfBirth_0' value='<? echo($this->birthday);?>'> 
		</p>
	</div>
	<div id="foafHomepage_container">
		<p>
			<span>Homepage: </span>
			<input id='foafHomepage_0' value='<? echo($this->homepage);?>'> 
		</p>
	</div>
</div>
