<?
//We don't want any HTML gubbins here
$this->layout()->setLayout('ajax');	
?>	
	<div class="fieldContainer">
		<div class="fieldLabelContainer">
			<span class="fieldLabel">Email</span>
		</div>
		<div class="fieldValueContainer" id="foafMbox_container">
			<input id='foafMbox_0' value=''>
		</div>
	</div>
	
	<div class="fieldContainer">
		<div class="fieldLabelContainer">
			<span class="fieldLabel">Phone</span>
		</div>
		<div class="fieldValueContainer" id="foafPhone_container">
			<input id='foafPhone_0' value=''>
		</div>
	</div>
	