<?
//TODO: build this whole thing out of javascript
//We don't want any HTML gubbins here
$this->layout()->setLayout('ajax');	
?>		
	
	<? /*
	    * need to add this stuff as an alternative to based_near
	    * 
	    * 
	    *  <contact:nearestAirport> 
      <wn:Airport>
        <air:name>Greater Binghamton Edwin A Link Fld</air:name>
        <air:iataCode>BGM</air:iataCode>
        <air:icaoCode>KBGM</air:icaoCode>
        <air:sameIndividualAs rdf:resource="http://www.daml.org/cgi-bin/airport?BGM"/>
        <air:location>Binghamton, New York, United States</air:location>
        <air:latitude>42.20861111111111</air:latitude>
        <air:longitude>-75.97972222222222</air:longitude>
        <air:elevation>1636</air:elevation>
       </wn:Airport>
    </contact:nearestAirport>
	    * 
	    */ ?>