<? 
        $this->layout()->setLayout('logon');

if (isset($_SERVER['PATH_INFO'])) {
        $path_info .= $_SERVER['PATH_INFO'];
	echo $path_info;
	error_log($path_info);
}


?>
<rdf:RDF
      xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
      xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
      xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"
      xmlns:bio="http://purl.org/vocab/bio/0.1/"
      xmlns:foaf="http://xmlns.com/foaf/0.1/"
      xmlns:admin="http://webns.net/mvcb/"
      xmlns:wn="http://xmlns.com/wordnet/1.6/"
	  xmlns:contact="http://www.w3.org/2000/10/swap/pim/contact#"
	  xmlns:air="http://dig.csail.mit.edu/TAMI/2007/amord/air#"
	  xmlns:dc="http://purl.org/dc/elements/1.1/"
	  >
	  
	  
<foaf:PersonalProfileDocument rdf:about="">
  <foaf:maker rdf:resource="#me"/>
  <foaf:primaryTopic rdf:resource="#me"/>
  <admin:generatorAgent rdf:resource="http://www.ldodds.com/foaf/foaf-a-matic"/>
  <admin:errorReportsTo rdf:resource="mailto:leigh@ldodds.com"/>
</foaf:PersonalProfileDocument>

<foaf:Person rdf:ID="me">
	<foaf:mbox_sha1sum>08d333c6437a2411f18a29b49e5a6a07649c9bf1</foaf:mbox_sha1sum>
	<foaf:mbox>mailto:luke.wilson-mawer@gmail.com</foaf:mbox>
	<foaf:depiction>
    	<foaf:Image rdf:about="http://plugin.org.uk/misc/steve-crop-sml.jpg">
    	   <dc:title>Steve Harris</dc:title>
    	   <dc:description>Picture of Steve from 2005</dc:description>
    	   <dc:format>image/jpeg</dc:format>
    	</foaf:Image>
  	</foaf:depiction>
	<foaf:birthday>12-06</foaf:birthday>
	<foaf:dateOfBirth>1983-12-06</foaf:dateOfBirth>
	<bio:event>
    	<bio:Birth>
     	 	<bio:date>1999-12-31</bio:date>
    	</bio:Birth>
 	</bio:event>
	<foaf:based_near geo:lat="51.47026" geo:long="0" geo:lat_long="51.46026,0"/>
	<foaf:based_near geo:lat="51.48026" geo:long="0" geo:lat_long="51.47026,0"/>	
	<foaf:holdsAccount>
		<foaf:OnlineAccount>
		<foaf:accountServiceHomepage rdf:resource="http://skype.com/"/>
		<foaf:accountName>luke</foaf:accountName>
		</foaf:OnlineAccount>
	</foaf:holdsAccount>
	<foaf:holdsAccount>
		<foaf:OnlineAccount>
		<foaf:accountServiceHomepage rdf:resource="http://del.icio.us"/>
		<foaf:accountProfilePage rdf:resource="http://del.icio.us/luke/"/>
		<foaf:accountName>luke</foaf:accountName>
		</foaf:OnlineAccount>
	</foaf:holdsAccount>
	<foaf:holdsAccount>
		<foaf:OnlineAccount>
		<foaf:accountServiceHomepage rdf:resource="http://del.icio.us"/>
		<foaf:accountProfilePage rdf:resource="http://del.icio.us/danbri/"/>
		<foaf:accountName>danbri</foaf:accountName>
		</foaf:OnlineAccount>
	</foaf:holdsAccount>	
	<foaf:name>Luke Wilson-Mawer</foaf:name>
	<foaf:title>Mr</foaf:title>
	<foaf:givenname>Luke</foaf:givenname>
	<foaf:family_name>Wilson-Mawer</foaf:family_name>
	<foaf:nick>mynicknamehere</foaf:nick>
	<foaf:homepage>http://luke.com</foaf:homepage>
	<foaf:homepage>http://gerryanderson.co.uk</foaf:homepage>
	<foaf:nick>lwm</foaf:nick>
	<foaf:mbox>mailto:luke.wilson-mawer@garlik.com</foaf:mbox>
	<foaf:mbox>mailto:lukewilsonmawer@gmail.com</foaf:mbox>
	<foaf:mbox>mailto:kim.song@barry.com</foaf:mbox>
	<foaf:mbox>mailto:luke.wilson-mawer@garlik.com</foaf:mbox>
	<foaf:phone>tel:07887432234</foaf:phone>
	<foaf:phone>tel:032327432234</foaf:phone>
	<foaf:mbox_sha1sum>cdd70a4226b1b980e49b6e3a85471ac4d94d7483</foaf:mbox_sha1sum>
	<foaf:depiction rdf:resource="http://profile.ak.facebook.com/profile5/267/125/n722905495_9884.jpg"/>
	<foaf:workplaceHomepage rdf:resource="http://www.garlik.com/"/>
	<foaf:schoolHomepage rdf:resource="http://www.ucl.ac.uk/"/>
	<foaf:knows>
		<foaf:Person>
			<foaf:name>Steve Harris</foaf:name>
			<foaf:mbox_sha1sum>26a374ad4de937252c044f7dd45aa48ecbdb4f16</foaf:mbox_sha1sum>
			<rdfs:seeAlso rdf:resource="http://plugin.org.uk/swh.xrdf"/>
		</foaf:Person>
	</foaf:knows>
	<foaf:knows>
	<foaf:Person>
		<foaf:name>Tom Ilube</foaf:name>
		<foaf:mbox_sha1sum>a8084b745be5ca1d33f89025be2587f8f92d6d52</foaf:mbox_sha1sum>
		<rdfs:seeAlso rdf:resource="http://qdos.com/people/tom.xrdf"/></foaf:Person>
	</foaf:knows>
	<foaf:knows>
		<foaf:Person>
			<foaf:name>Gurpreet Syan</foaf:name>
			<foaf:mbox_sha1sum>e3df651c653b04f78815cedc8d6c43b754678188</foaf:mbox_sha1sum>
		</foaf:Person>
	</foaf:knows>
	<contact:home rdf:parseType="Resource">
	<rdf:type rdf:resource="http://www.w3.org/2000/10/swap/pim/contact#ContactLocation"/>
		<contact:address rdf:parseType="Resource">
			<contact:city>Fontainebleau</contact:city>
			<contact:country>France</contact:country>
			<contact:postalCode>77300</contact:postalCode>
			<contact:street>21 rue Saint Honore</contact:street>
		</contact:address>
		<geo:lat>48.404532</geo:lat>
		<geo:long>2.700448</geo:long>
	</contact:home>
	<contact:office rdf:parseType="Resource">
	<rdf:type rdf:resource="http://www.w3.org/2000/10/swap/pim/contact#ContactLocation"/>
		<contact:address rdf:parseType="Resource">
			<contact:city>Fontainebleau office</contact:city>
			<contact:country>France office</contact:country>
			<contact:postalCode>77400</contact:postalCode>
			<contact:street>26 rue Saint Honore</contact:street>
		</contact:address>
		<geo:lat>48.405</geo:lat>
		<geo:long>2.701</geo:long>
	</contact:office>
	<contact:nearestAirport>
		<wn:Airport air:icao="EGGD" air:iata="BRS"/>
	</contact:nearestAirport>
</foaf:Person>

</rdf:RDF>
