<?
//TODO: need to generate forms for input elements to aid with eventual w3c compliance
?>
<table cellspacing="10">
	<tr>
		<td>
			<form action = "javascript:clearFoaf();">
					<input type = 'submit' value = "Start Again" />
			</form>
		</td>
		<td>
			<form id="otherFormpublicprivate" action="javascript:writePublicAndPrivate()">
				<input class="otherButton" type="submit" value="Write both"/>
			</form>
		</td>
		<td>
			<form id="otherFormprivate" action="javascript:writePrivate()">
				<input class="otherButton" type="submit" value="Write private"/>
			</form>
		</td>
		<td>
			<form id="otherFormpublic" action="javascript:writePublic()">
				<input class="otherButton" type="submit" value="Write public"/>
			</form>
		</td>
		<td>
			<form action="javascript:write('private')">
				<input class="otherButton" type="submit" value="Download private"/>
			</form>
		</td>
		<td>
			<form action="javascript:write('public')">
				<input class="otherButton" type="submit" value="Download public"/>
			</form>
		</td>
		<td>
			<img src='/images/ajax-loader.gif' id='ajaxLoader'/>
		</td>
	</tr>
</table>


<?
//TODO: need to generate forms for input elements to aid with eventual w3c compliance
?>
		
<div id="leftCol">
<form action="#">
	<? //TODO: perhaps the load-the-basics name should be generated somehow ?>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="saveFoaf();loadFoaf('load-the-basics');" class="editorElement">
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" id="load-the-basics" class="editorTitle">
				<div class="editorTitleText">The basics </div>
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Title
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleOdd">
				Given Name 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Family Name 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleOdd">
				Real Name 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Nickname 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Birthday 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Interests
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="saveFoaf();loadFoaf('load-contact-details');" class="editorElement">
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" id='load-contact-details' class="editorTitle">
				<div class="editorTitleText">Contact details </div>
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Email 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleOdd">
				Phones 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Addresses 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="saveFoaf();loadFoaf('load-pictures');" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-pictures" class="editorTitle">
				<div class="editorTitleText">Pictures </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Main Image 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Others 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="saveFoaf();loadFoaf('load-locations');" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-locations" class="editorTitle">
				<div class="editorTitleText">Locations </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Nearest Airport 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				I'm Based Near 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="saveFoaf();loadFoaf('load-accounts');" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-accounts" class="editorTitle">
				<div class="editorTitleText">Accounts </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				My Accounts 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Blogs
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Homepages 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="saveFoaf();loadFoaf('load-friends');" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-friends" class="editorTitle">
				<div class="editorTitleText">Friends </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Mutual Friends 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				People who know me
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				People I know
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="saveFoaf();loadFoaf('load-other');" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-other" class="editorTitle">
				<div class="editorTitleText">Geek View </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Private
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Public
			</div>
		</div>
	</form>
</div><!-- end leftCol -->

<div class="rightCol" id="personal">


</div>
<!-- hidden div for autocomplete to work for airports. TODO: configure this in a more straightforward way -->
	<div id='airport_autocomplete'>
	<input type="text" value="Find an airport" onclick="if(this.value=='Find an airport'){this.value='';}" id="CityLocal" autocomplete="off" class="ac_input" style=""/>
</div>
	
<script type='text/javascript'>
	loadFoaf('load-the-basics');
</script>
