<?
//TODO: need to generate forms for input elements to aid with eventual w3c compliance
?>
<table cellspacing="10">
	<tr>
		<td><form action = "javascript:renderOther();">
			<p>Click to write your FOAF file:	
					<input type = 'text' id= 'writeUri' name = 'writeUri'/>
					<input type = 'submit' value = "Write" />
			</p>
			</form>
		</td>
		<td>
			<form action = "javascript:clearFoaf();">
					<input type = 'submit' value = "Start Again" />
			</form>
		</td>
		<td>
			<img src='/images/ajax-loader.gif' id='ajaxLoader'/>
		</td>
	</tr>
</table>


<?
//TODO: need to generate forms for input elements to aid with eventual w3c compliance
?>
		
<div id="leftCol">
<form action="#">
	<? //TODO: perhaps the load-the-basics name should be generated somehow ?>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="loadFoaf('load-the-basics');saveFoaf();" class="editorElement">
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" id="load-the-basics" class="editorTitle">
				<img alt="basics" class="editorElementIcon" src="/images/basics_icon.gif"/>
				<div class="editorTitleText">The basics </div>
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Title
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleOdd">
				Given Name 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Family Name 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleOdd">
				Real Name 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Nickname 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Birthday 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Interests
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="loadFoaf('load-contact-details');saveFoaf();" class="editorElement">
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" id='load-contact-details' class="editorTitle">
				<img alt="contact" class="editorElementIcon" src="/images/contact_icon.gif"/>
				<div class="editorTitleText">Contact details </div>
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Email 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleOdd">
				Phones 
			</div>
			<div  onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" class="editorSubTitleEven">
				Addresses 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="loadFoaf('load-pictures');saveFoaf();" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-pictures" class="editorTitle">
				<img alt="pictures" class="editorElementIcon" src="/images/pictures_icon.gif"/>
				<div class="editorTitleText">Pictures </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Main Image 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Others 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="loadFoaf('load-locations');saveFoaf();" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-locations" class="editorTitle">
				<img alt="accounts" class="editorElementIcon" src="/images/accounts_icon.gif"/>
				<div class="editorTitleText">Locations </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Nearest Airport 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				I'm Based Near 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="loadFoaf('load-accounts');saveFoaf();" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-accounts" class="editorTitle">
				<img alt="accounts" class="editorElementIcon" src="/images/accounts_icon.gif"/>
				<div class="editorTitleText">Accounts </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				My Accounts 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Blogs
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Homepages 
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="loadFoaf('load-friends');saveFoaf();" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-friends" class="editorTitle">
				<img alt="friends" class="editorElementIcon" src="/images/friends_icon.gif"/>
				<div class="editorTitleText">Friends </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Mutual Friends 
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				People who know me
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				People I know
			</div>
		</div>
		<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'" onclick="loadFoaf('load-other');saveFoaf();" class="editorElement">
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  id="load-other" class="editorTitle">
				<img alt="other" class="editorElementIcon" src="/images/other_icon.gif"/>
				<div class="editorTitleText">Geek View </div>
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleEven">
				Private
			</div>
			<div onmouseover="this.style.cursor='pointer'" onmouseout="this.style.cursor='default'"  class="editorSubTitleOdd">
				Public
			</div>
		</div>
	</form>
</div><!-- end leftCol -->

<div class="rightCol" id="personal">


</div>
<!-- hidden div for autocomplete to work for airports. TODO: configure this in a more straightforward way -->
	<div id='airport_autocomplete'>
	<input type="text" value="Find an airport" onclick="if(this.value=='Find an airport'){this.value='';}" id="CityLocal" autocomplete="off" class="ac_input" style=""/>
</div>
	
<script type='text/javascript'>
	loadFoaf('load-the-basics');
	document.getElementById('writeUri').value ='<? echo($this->uri); ?>';
</script>