<?
//TODO: need to generate forms for input elements to aid with eventual w3c compliance
?>
<div id='foafUrlContainer'>
		<?php if(property_exists($this,'publicUri') && $this->publicUri){
                                echo("<div class='foafUrlTitle'>Your Public FOAF URI: </div><div class='foafUrl'>".$this->publicUri."</div>");
                } ?>
		<br/>

		<?php if(property_exists($this,'privateUri') && $this->privateUri){
                                echo("<div class='foafUrlTitle'>Your Private FOAF URI: </div><div class='foafUrl'>".$this->privateUri."</div>");
                } ?>
		
</div>
<table cellspacing="10">
<tr>
	<td>
		<form action = "javascript:clearFoaf();">
			<input type = 'submit' value = "Start Again" />
		</form>
	</td>
	<td>
		<form id="otherFormpublicprivate" action="javascript:writePublicAndPrivate()">
			<input class="otherButton" type="submit" value="Save Data"/>
		</form>
	</td>
	<td>
		<form id="otherFormadvance" action="/advance">
			<input class="otherButton" type="submit" value="Advanced Writing"/>
		</form>
	</td>
	<td id='saveInfo'>

        </td>
	<td>
		<img src='/images/ajax-loader.gif' id='ajaxLoader'/>
	</td>
	<td>
	</td>
</tr>
</table>


<?
//TODO: need to generate forms for input elements to aid with eventual w3c compliance
?>
	
<div id="leftCol">
<form action="#">
<? //TODO: perhaps the load-the-basics name should be generated somehow ?>
	<div  onclick="saveFoaf();loadFoaf('load-the-basics');" class="editorElement">
		<div   id="load-the-basics" class="editorTitle">
			<div class="editorTitleText">The basics </div>
		</div>
		<div   class="editorSubTitleEven">
			Title
		</div>
		<div   class="editorSubTitleOdd">
			Given Name 
		</div>
		<div   class="editorSubTitleEven">
			Family Name 
		</div>
		<div   class="editorSubTitleOdd">
			Real Name 
		</div>
		<div   class="editorSubTitleEven">
			Nickname 
		</div>
		<div   class="editorSubTitleOdd">
			Birthday 
		</div>
	</div>
	<div  onclick="saveFoaf();loadFoaf('load-contact-details');" class="editorElement">
		<div   id='load-contact-details' class="editorTitle">
			<div class="editorTitleText">Contact details </div>
		</div>
		<div   class="editorSubTitleEven">
			Email 
		</div>
		<div   class="editorSubTitleOdd">
			Phones 
		</div>
<!--		<div   class="editorSubTitleEven">
			Addresses 
		</div> -->
	</div>
	<div  onclick="saveFoaf();loadFoaf('load-pictures');" class="editorElement">
		<div   id="load-pictures" class="editorTitle">
			<div class="editorTitleText">Pictures </div>
		</div>
		<div   class="editorSubTitleEven">
			Main Image 
		</div>
		<div   class="editorSubTitleOdd">
			Others 
		</div>
	</div>
	<div  onclick="saveFoaf();loadFoaf('load-locations');" class="editorElement">
		<div   id="load-locations" class="editorTitle">
			<div class="editorTitleText">Locations </div>
		</div>
		<div   class="editorSubTitleEven">
			Nearest Airport 
		</div>
		<div   class="editorSubTitleOdd">
			Based Near 
		</div>
	</div>
	<div  onclick="saveFoaf();loadFoaf('load-accounts');" class="editorElement">
		<div   id="load-accounts" class="editorTitle">
			<div class="editorTitleText">Accounts </div>
		</div>
		<div   class="editorSubTitleEven">
			My Accounts 
		</div>
		<div   class="editorSubTitleOdd">
			Blogs
		</div>
		<div   class="editorSubTitleEven">
			Personal Homepages 
		</div>
	</div>
	<div  onclick="saveFoaf();loadFoaf('load-friends');" class="editorElement">
		<div   id="load-friends" class="editorTitle">
			<div class="editorTitleText">Friends </div>
		</div>
		<div   class="editorSubTitleEven">
			Mutual Friends 
		</div>
		<div   class="editorSubTitleOdd">
			Friend Requests	
		</div>
		<div   class="editorSubTitleEven">
			My Friends
		</div>
	</div>
	<div  onclick="saveFoaf();loadFoaf('load-interests');" class="editorElement">
		<div   id="load-interests" class="editorTitle">
			<div class="editorTitleText">Interests </div>
		</div>
		<div   class="editorSubTitleEven">
			Interests
		</div>
	</div>
	<div  onclick="saveFoaf();loadFoaf('load-other');" class="editorElement">
		<div   id="load-other" class="editorTitle">
			<div class="editorTitleText">Geek View </div>
		</div>
		<div   class="editorSubTitleEven">
			Private::
		</div>
		<div   class="editorSubTitleOdd">
			Public
		</div>
	</div>
</form>
</div><!-- end leftCol -->

<div class="rightCol" id="personal">


</div>
<!-- hidden div for autocomplete to work for airports. TODO: configure this in a more straightforward way -->
<div id='airport_autocomplete'>
<input type="text" value="Find an airport" onclick="if(this.value=='Find an airport'){this.value='';}" id="CityLocal" autocomplete="off" class="ac_input" style=""/>
</div>

<script type='text/javascript'>
	loadFoaf('load-the-basics');
	var authenticated = <?php echo($this->authenticated); ?>
</script>
