<?	
	//We don't want to laod all the scripts
	$this->layout()->setLayout('continue');
?>
<div id="content">
			<div class="">
				<h2>
					In order to continue writing to our servers please authenicate with your OpenID
				</h2>
				<!--<form method='post' id='openidForm' action='javascript:doOpenid()'>-->
				<form method='post' id='openidForm' action='/continue/do-openid'>
					<p>
						Please enter your OpenID below.  If you don't have an openId, click <a href='http://openid.net/get/'>here</a> to find out how.
					</p>
					<span>OpenID:    </span><input id='openid_identifier' class='urlField' name='openid_identifier' value=''><br/>
					<p><small>For example, fnivramd.livejournal.com</small></p>
					<input id='openid_action' name='openid_action' type='submit' value='login'/>&nbsp;&nbsp;&nbsp;<img src='/images/ajax-loader.gif' id='ajaxLoader'/>

				</form>
			</div>
</div><!-- end content -->

			<!-- footer -->
