<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Foaf Editor</title>
        <link media="screen" type="text/css" rel="stylesheet" href="/style/style.css">
        <script type="text/javascript" src="/js/json.js"></script>
        <script type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>
        <script type="text/javascript" src="/js/script.js"></script>
        <script>
        	/*global variables containing all the data on the page*/
			var PageDataObject;
			
			/*object to hold global variables in */
			//TODO: this object is a bit 'inside out'
			function PageDataObject(){
				this.foafPrimaryTopic = new Array();
        		<?
        			//TODO: this'll have to change if we make the fieldNames object page specific
    				require_once 'FieldNames.php';
    				require_once 'Field.php';
    				
    				$fieldNamesObject = new FieldNames();
    				$allFieldNames = $fieldNamesObject->getAllFieldNames();
    				 
    				/*generate javascript to declare an array for each field on the page*/
    				foreach($allFieldNames as $fieldName => $field){
    					echo("this.".$fieldName."ValueArray = new Array();"."\n");
    				}
    	    	
        		?>	
			}
		</script>
    </head>
    <body>
        <div id="main_container">
        	<div id="header">
            	<div id="qdos_logo">
               		<a href="http://qdos.com/">  
                    	<img border="0" alt="QDOS" src="/images/qdos_logo_beta.gif"/>
                	</a>
               	</div>
                	<form action="find">
                    	<h1 id="search_for_another">Search for another profile</h1>
                       	<input name="q" value="" id="search_box_top"/>
                        <a href="javascript:document.forms[0].submit()"><img border="0" img id="find_button" src="/images/find.gif"/></a>
                    </form>
                </div>
                 <div id="content">
                 	<?php echo $this->layout()->content; ?>
                 </div><!-- end content -->

				 <!-- footer -->
				 <div id="footer">
					<div id="foot_nav">
						<ul>
							<li><a href="http://qdos.com/terms" title="Terms &amp; Conditions" id="terms">Terms &amp; Conditions</a></li>
							<li><a href="http://qdos.com/privacy" title="Privacy" id="privacy">Privacy</a></li>
							<li><a href="http://qdos.com/faqs" title="Faqs" id="faqs">Faqs</a></li>
							<li><a href="http://qdos.com/developers" title="Developers" id="developers">Developers</a></li>
							<li><a href="http://qdos.com/apps" title="Applications" id="applications">Applications</a></li>
						</ul>
					</div>
				</div><!-- /footer -->
			</div>
	</body>
</html>
                 
  