<?
require_once 'FieldNames.php';
require_once 'Field.php';

//TODO: only grab maps data when we need it.
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <title>Foaf Editor</title>
        <link media="screen" type="text/css" rel="stylesheet" href="/style/style.css"/>
        <link media="screen" type="text/css" rel="stylesheet" href="/style/autocomplete.css"/>
        <script type="text/javascript" src="/js/json.js"></script>
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/autocomplete.js"></script>
        <script type="text/javascript" src="/js/script.js"></script>
        <script type="text/javascript" src="/js/calendar.js"></script>
        <!--<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAApqXhYSoDqQ0Y0DYX4UfSxxSLWDsn3RuQVVZfehfh-L1M5gleqBRHZtgTA3yW_26SUBV5t3j0_6x3AA" type="text/javascript"></script>-->
        <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAApbHmnd7Fl5gfAZFm7R5qsRT3kDWp0B3HJYoHKKfCcP8PJ9L5mRTnK_evfZgGX0-21gt_FKv3_Yn47g" type="text/javascript"></script>
        <script type="text/javascript" src="/js/utils.js"></script>
        <script type="text/javascript" src="/js/loadData.js"></script>
    </head>
    <body>
        <div id="main_container">
        	<div id="header">
            	    <div id="qdos_logo">
               		<a href="http://qdos.com/"><img border="0" alt="QDOS" src="/images/qdos_logo_beta.gif"/></a>
               	    </div>
                    <form action="find">
                    	<h1 id="search_for_another">Search for another profile</h1>
                       	<input name="q" value="" id="search_box_top"/>
                        <a href="javascript:document.forms[0].submit()"><img border="0" alt="Find" id="find_button" src="/images/find.gif"/></a>
                    </form>
                </div>
                <div id="content">
                	<img src='/images/foafbuilder_logo.png' class='builderLogo' alt='FOAF Builder Logo'/>
                 	<?php echo $this->layout()->content; ?>
                </div><!-- end content -->

		 <!-- footer -->
		 <div id="footer">
		 	<div id="foot_nav">
			    <ul>
				<li><a href="http://qdos.com/terms" title="Terms &amp; Conditions" id="terms">Terms &amp; Conditions</a></li>
				<li><a href="http://qdos.com/privacy" title="Privacy" id="privacy">Privacy</a></li>
				<li><a href="http://qdos.com/faqs" title="Faqs" id="faqs">Faqs</a></li>
				<li><a href="http://qdos.com/developers" title="Developers" id="developers">Developers</a></li>
				<li><a href="http://qdos.com/apps" title="Applications" id="applications">Applications</a></li>
			    </ul>
			</div>
		</div><!-- /footer -->
	</div>
	
    </body>
</html>

           
  
